<a href="https://colab.research.google.com/github/BDonadelli/Codigos-em-financas/blob/main/Dividendos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import datetime

url = 'http://dividendobr.com/tabexregra2.php'
df = pd.read_html(url)

def traduz_mes(mes):
    
    mes = mes.lower()

    if mes == 'janeiro': mes = 'January'
    elif mes == 'fevereiro': mes = 'February'
    elif mes == 'março': mes = 'March'
    elif mes == 'abril': mes = 'April'
    elif mes == 'maio': mes = 'May'
    elif mes == 'junho': mes = 'June'
    elif mes == 'julho': mes = 'July'
    elif mes == 'agosto': mes = 'August'
    elif mes == 'setembro': mes = 'September'
    elif mes == 'outubro': mes = 'October'
    elif mes == 'novembro': mes = 'November'
    elif mes == 'dezembro': mes = 'December'
    
    return mes

In [2]:
table = pd.DataFrame(columns=['Ticker','Ativo', 'Mercado', 'Tipo', 
                              'Aprovação','Data ex', 'Pagamento' ,'Valor'], 
                              index=list(range(0,300)))

In [3]:
n=0
for i in list(range(0,len(df))):
    if i==0:
        n = i


    table['Ativo'][n] = df[i][1][0]
    table['Tipo'][n] = df[i][1][2]
    table['Valor'][n] = df[i][1][5].split(' ')[1]
    #data de aprovação
    d = df[i][1][1].split(' ')[1]
    m = df[i][1][1].split(' ')[3]
    a = df[i][1][1].split(' ')[5]
    m_pt_en = traduz_mes(m)
    data = m_pt_en +' '+ d + ', ' + a
    data = datetime.datetime.strptime(data, '%B %d, %Y')
    table['Aprovação'][n] = data.date()
    
    #data ex
    d = df[i][1][3].split(' ')[1]
    m = df[i][1][3].split(' ')[3]
    a = df[i][1][3].split(' ')[5]
    m_pt_en = traduz_mes(m)
    data = m_pt_en +' '+ d + ', ' + a
    data = datetime.datetime.strptime(data, '%B %d, %Y')
    table['Data ex'][n] = data.date()


    #Previsão de pagamento
    if df[i][1][4] == 'data não disponível':
        table['Pagamento'][n] = 'data não disponível'
    else: 
        d = df[i][1][4].split(' ')[1]
        m = df[i][1][4].split(' ')[3]
        a = df[i][1][4].split(' ')[5]
        m_pt_en = traduz_mes(m)
        data = m_pt_en +' '+ d + ', ' + a
        data = datetime.datetime.strptime(data, '%B %d, %Y')
        table['Pagamento'][n] = data.date()


    #Mercado/Ticker
    if 'ON' in df[i][1][5]:
        table['Mercado'][n] = 'ON'
        table['Ticker'][n] = df[i][1][0].split(' ')[0] + '3'
    elif 'PN' in df[i][1][5]:
        table['Mercado'][n] = 'PN'
        table['Ticker'][n] = df[i][1][0].split(' ')[0] + '4'
    elif 'UNIT' in df[i][1][5]:
        table['Mercado'][n] = 'UNIT'
        table['Ticker'][n] = df[i][1][0].split(' ')[0] + '11'


    if len(df[i]) == 7:
        table.iloc[n+1] = table.loc[n]
        #Mercado/Ticker
        if 'ON' in df[i][1][6]:
            table['Mercado'][n+1] = 'ON'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '3'
        elif 'PN' in df[i][1][6]:
            table['Mercado'][n+1] = 'PN'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '4'
        elif 'UNIT' in df[i][1][6]:
            table['Mercado'][n+1] = 'UNIT'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '11'
        n += 1


    if len(df[i]) == 8:
        table.iloc[n+1] = table.loc[n]
        #Mercado/Ticker
        if 'ON' in df[i][1][7]:
            table['Mercado'][n+1] = 'ON'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '3'
        elif 'PN' in df[i][1][7]:
            table['Mercado'][n+1] = 'PN'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '4'
        elif 'UNIT' in df[i][1][7]:
            table['Mercado'][n+1] = 'UNIT'
            table['Ticker'][n+1] = df[i][1][0].split(' ')[0] + '11'
        n += 1
    n += 1
    if i == len(df): break
    
# table = table.set_index('Ticker')
table.dropna(inplace=True)

In [4]:
table['Ativo'] = table['Ativo'].str[:4]
table['Tipo'] = table['Tipo'].replace('Juros Sobre Capital Próprio', 'JCP')
table['Tipo'] = table['Tipo'].replace('Dividendo', 'Div')

In [5]:
from IPython.display import display, HTML
display(HTML(table[['Ticker','Tipo','Aprovação','Data ex','Pagamento','Valor']].to_html(index=False)))